In [1]:
from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np

# load the data
dataset = pd.read_csv('dataset9000.data', header=None)
print(dataset.head())
X = np.array(dataset.iloc[:, 0:17])
print(X)
Y = np.array(dataset.iloc[:, 17])
print(Y)
dataset.columns = ["Database Fundamentals", "Computer Architecture", "Distributed Computing Systems",
                   "Cyber-Security", "Networking", "Development", "Programming Skills", "Project Management",
                   "Computer Forensics Fundamentals", "Technical Communication", "AI ML", "Software Engineering",
                   "Business Analysis", "Communication skills", "Data Science", "Troubleshooting-skills",
                   "Graphics Designing", "Roles"]
dataset.dropna(how='all', inplace=True)

seed = 5
kfold = model_selection.KFold(n_splits=15, shuffle=True, random_state=seed)

# initialize the base classifier
base_cls = DecisionTreeClassifier()

# no. of base classifier
num_trees = 50

# bagging classifier
model = BaggingClassifier(base_estimator=base_cls,
                          n_estimators=num_trees,
                          random_state=seed)

results = model_selection.cross_val_score(model, X, Y, cv=kfold)
print("accuracy:", results.mean() * 100)


   0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
0   9   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   
1   9   2   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   
2   9   3   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   
3   9   5   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   
4   9   6   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   

                       17  
0  Database Administrator  
1  Database Administrator  
2  Database Administrator  
3  Database Administrator  
4  Database Administrator  
[[9 1 1 ... 1 1 1]
 [9 2 1 ... 1 1 1]
 [9 3 1 ... 1 1 1]
 ...
 [1 1 1 ... 6 6 9]
 [1 1 1 ... 7 7 9]
 [1 1 1 ... 7 5 9]]
['Database Administrator' 'Database Administrator'
 'Database Administrator' ... 'Graphics Designer' 'Graphics Designer'
 'Graphics Designer']


c:\Users\anura\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
c:\Users\anura\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
c:\Users\anura\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
c:\Users\anura\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
c:\Users\anura\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\ensemble\_base.py:156: Futu

accuracy: 100.0
